-- ============================================================
-- Flyway V10: anh/brand/rating cho san pham + catalog dien tu that.
-- Nguon data: DummyJSON (https://dummyjson.com) - dataset demo cong khai, anh CDN.
-- Gia quy doi USD -> VND (x25000), lam tron nghin. Sinh tu scripts/gen-seed.mjs.
-- ============================================================

ALTER TABLE products ADD COLUMN image_url VARCHAR(512);
ALTER TABLE products ADD COLUMN brand     VARCHAR(128);
ALTER TABLE products ADD COLUMN rating    NUMERIC(3, 2);

-- Chuan hoa ten category (them dau) + bo sung nhom dien tu
UPDATE categories SET name = 'Điện thoại' WHERE id = 1;
UPDATE categories SET name = 'Sách'       WHERE id = 3;
INSERT INTO categories (id, name) VALUES
    (4, 'Máy tính bảng'),
    (5, 'Phụ kiện'),
    (6, 'Đồng hồ');

-- Backfill 4 san pham seed cu
UPDATE products SET brand = 'Apple',   rating = 4.7, image_url = 'https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp'  WHERE id = 1;
UPDATE products SET brand = 'Samsung', rating = 4.5, image_url = 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp' WHERE id = 2;
UPDATE products SET brand = 'Apple',   rating = 4.8, image_url = 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp'     WHERE id = 3;

-- Catalog dien tu (48 san pham)
INSERT INTO products (id, name, description, price, stock_quantity, category_id, deleted, version, image_url, brand, rating, created_at, updated_at, created_by) VALUES
    (5, 'iPhone 5s', 'The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it''s an older model, it still provides a reliable user experience.', 5000000, 25, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp', 'Apple', 2.83, now(), now(), 'system'),
    (6, 'iPhone 6', 'The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.', 7500000, 60, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp', 'Apple', 3.41, now(), now(), 'system'),
    (7, 'iPhone 13 Pro', 'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.', 27500000, 56, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp', 'Apple', 4.12, now(), now(), 'system'),
    (8, 'iPhone X', 'The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.', 22500000, 37, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp', 'Apple', 2.51, now(), now(), 'system'),
    (9, 'Oppo A57', 'The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.', 6250000, 19, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp', 'Oppo', 3.94, now(), now(), 'system'),
    (10, 'Oppo F19 Pro Plus', 'The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.', 10000000, 78, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp', 'Oppo', 3.51, now(), now(), 'system'),
    (11, 'Oppo K1', 'The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.', 7500000, 55, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp', 'Oppo', 4.25, now(), now(), 'system'),
    (12, 'Realme C35', 'The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.', 3750000, 48, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp', 'Realme', 4.2, now(), now(), 'system'),
    (13, 'Realme X', 'The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.', 7500000, 12, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp', 'Realme', 3.7, now(), now(), 'system'),
    (14, 'Realme XT', 'The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.', 8750000, 80, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp', 'Realme', 4.58, now(), now(), 'system'),
    (15, 'Samsung Galaxy S7', 'The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.', 7500000, 67, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp', 'Samsung', 3.3, now(), now(), 'system'),
    (16, 'Samsung Galaxy S8', 'The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.', 12500000, 0, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp', 'Samsung', 4.4, now(), now(), 'system'),
    (17, 'Samsung Galaxy S10', 'The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.', 17500000, 19, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp', 'Samsung', 3.06, now(), now(), 'system'),
    (18, 'Vivo S1', 'The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.', 6250000, 50, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp', 'Vivo', 3.5, now(), now(), 'system'),
    (19, 'Vivo V9', 'The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.', 7500000, 82, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp', 'Vivo', 3.6, now(), now(), 'system'),
    (20, 'Vivo X21', 'The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.', 12500000, 7, 1, FALSE, 0, 'https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp', 'Vivo', 4.26, now(), now(), 'system'),
    (21, 'Apple MacBook Pro 14 Inch Space Grey', 'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.', 50000000, 24, 2, FALSE, 0, 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp', 'Apple', 3.65, now(), now(), 'system'),
    (22, 'Asus Zenbook Pro Dual Screen Laptop', 'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.', 45000000, 45, 2, FALSE, 0, 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp', 'Asus', 3.95, now(), now(), 'system'),
    (23, 'Huawei Matebook X Pro', 'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.', 35000000, 75, 2, FALSE, 0, 'https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp', 'Huawei', 4.98, now(), now(), 'system'),
    (24, 'Lenovo Yoga 920', 'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.', 27500000, 40, 2, FALSE, 0, 'https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp', 'Lenovo', 2.86, now(), now(), 'system'),
    (25, 'New DELL XPS 13 9300 Laptop', 'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.', 37500000, 74, 2, FALSE, 0, 'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp', 'Dell', 2.67, now(), now(), 'system'),
    (26, 'iPad Mini 2021 Starlight', 'The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.', 12500000, 47, 4, FALSE, 0, 'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp', 'Apple', 3.18, now(), now(), 'system'),
    (27, 'Samsung Galaxy Tab S8 Plus Grey', 'The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it''s ideal for productivity and entertainment.', 15000000, 62, 4, FALSE, 0, 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp', 'Samsung', 4.68, now(), now(), 'system'),
    (28, 'Samsung Galaxy Tab White', 'The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.', 8750000, 92, 4, FALSE, 0, 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp', 'Samsung', 3.72, now(), now(), 'system'),
    (29, 'Amazon Echo Plus', 'The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.', 2500000, 61, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp', 'Amazon', 4.99, now(), now(), 'system'),
    (30, 'Apple Airpods', 'The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.', 3250000, 67, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp', 'Apple', 4.15, now(), now(), 'system'),
    (31, 'Apple AirPods Max Silver', 'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.', 13750000, 59, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp', 'Apple', 3.47, now(), now(), 'system'),
    (32, 'Apple Airpower Wireless Charger', 'The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.', 2000000, 1, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp', 'Apple', 3.68, now(), now(), 'system'),
    (33, 'Apple HomePod Mini Cosmic Grey', 'The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience.', 2500000, 27, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp', 'Apple', 4.62, now(), now(), 'system'),
    (34, 'Apple iPhone Charger', 'The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.', 500000, 31, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp', 'Apple', 4.15, now(), now(), 'system'),
    (35, 'Apple MagSafe Battery Pack', 'The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.', 2500000, 1, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp', 'Apple', 3.62, now(), now(), 'system'),
    (36, 'Apple Watch Series 4 Gold', 'The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.', 8750000, 33, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp', 'Apple', 2.74, now(), now(), 'system'),
    (37, 'Beats Flex Wireless Earphones', 'The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.', 1250000, 50, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp', 'Beats', 4.24, now(), now(), 'system'),
    (38, 'iPhone 12 Silicone Case with MagSafe Plum', 'The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.', 750000, 69, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp', 'Apple', 3.62, now(), now(), 'system'),
    (39, 'Monopod', 'The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease.', 500000, 48, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp', 'TechGear', 4.43, now(), now(), 'system'),
    (40, 'Selfie Lamp with iPhone', 'The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos.', 375000, 58, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp', 'GadgetMaster', 3.55, now(), now(), 'system'),
    (41, 'Selfie Stick Monopod', 'The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras.', 325000, 11, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp', 'SnapTech', 3.88, now(), now(), 'system'),
    (42, 'TV Studio Camera Pedestal', 'The TV Studio Camera Pedestal is a professional-grade camera support system for smooth and precise camera movements in a studio setting. Ideal for broadcast and production.', 12500000, 15, 5, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp', 'ProVision', 2.78, now(), now(), 'system'),
    (43, 'Brown Leather Belt Watch', 'The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.', 2250000, 32, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp', 'Fashion Timepieces', 4.19, now(), now(), 'system'),
    (44, 'Longines Master Collection', 'The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it''s a symbol of luxury and sophistication.', 37500000, 100, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp', 'Longines', 3.87, now(), now(), 'system'),
    (45, 'Rolex Cellini Date Black Dial', 'The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex''s heritage.', 225000000, 40, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp', 'Rolex', 4.97, now(), now(), 'system'),
    (46, 'Rolex Cellini Moonphase', 'The Rolex Cellini Moonphase is a masterpiece of horology, featuring a moon phase complication and exquisite design. It reflects Rolex''s commitment to precision and elegance.', 325000000, 36, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp', 'Rolex', 2.58, now(), now(), 'system'),
    (47, 'Rolex Datejust', 'The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it''s a symbol of Rolex''s watchmaking excellence.', 275000000, 86, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp', 'Rolex', 3.66, now(), now(), 'system'),
    (48, 'Rolex Submariner Watch', 'The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it''s a symbol of adventure and exploration.', 350000000, 55, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp', 'Rolex', 2.69, now(), now(), 'system'),
    (49, 'IWC Ingenieur Automatic Steel', 'The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.', 125000000, 90, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp', 'IWC', 2.93, now(), now(), 'system'),
    (50, 'Rolex Datejust Women', 'The Rolex Datejust Women''s watch is an iconic timepiece designed for women. With a timeless design and a date complication, it offers both elegance and functionality.', 275000000, 4, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp', 'Rolex', 2.86, now(), now(), 'system'),
    (51, 'Watch Gold for Women', 'The Gold Women''s Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.', 20000000, 0, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp', 'Fashion Gold', 4.24, now(), now(), 'system'),
    (52, 'Women''s Wrist Watch', 'The Women''s Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.', 3250000, 12, 6, FALSE, 0, 'https://cdn.dummyjson.com/product-images/womens-watches/women''s-wrist-watch/thumbnail.webp', 'Fashion Co.', 3.52, now(), now(), 'system');

-- Day sequence len qua id chen tay
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));
SELECT setval(pg_get_serial_sequence('products', 'id'),   (SELECT MAX(id) FROM products));
