-- ============================================================
-- Flyway V3: bang cho cac tinh nang Nhom 2/5 (gio hang, danh gia, nhat ky dang nhap).
-- Chay o profile postgres (dev H2 dung create-drop nen tu tao).
-- ============================================================

CREATE TABLE carts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id)
);

CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT NOT NULL REFERENCES carts (id),
    product_id BIGINT NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL
);

CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    user_id    BIGINT NOT NULL REFERENCES users (id),
    rating     INTEGER NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE login_events (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    outcome  VARCHAR(20) NOT NULL,
    ip       VARCHAR(64),
    at       TIMESTAMP WITH TIME ZONE NOT NULL
);
