-- ============================================================
-- Flyway V6: nhat ky bien dong ton kho (append-only) - doi soat nhap/xuat kho.
-- ============================================================
CREATE TABLE inventory_movements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products (id),
    change_qty INTEGER NOT NULL,
    reason     VARCHAR(20) NOT NULL,
    order_id   BIGINT REFERENCES orders (id),
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255)
);

CREATE INDEX idx_inv_mov_product ON inventory_movements (product_id);
CREATE INDEX idx_inv_mov_order ON inventory_movements (order_id);
