-- ============================================================
-- Flyway V7: ma giam gia (coupon) + cot giam gia tren don hang.
-- ============================================================
CREATE TABLE coupons (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(64) NOT NULL UNIQUE,
    type             VARCHAR(16) NOT NULL,
    value            NUMERIC(12, 2) NOT NULL,
    min_order_amount NUMERIC(12, 2),
    max_uses         INTEGER,
    used_count       INTEGER NOT NULL DEFAULT 0,
    valid_from       TIMESTAMP,
    valid_to         TIMESTAMP,
    active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255)
);

-- Don hang: luu so tien giam + ma coupon da ap (de tra ve / doi soat).
ALTER TABLE orders ADD COLUMN discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN coupon_code VARCHAR(64);

-- Vai coupon mau de thu.
INSERT INTO coupons (code, type, value, min_order_amount, max_uses, active)
VALUES ('WELCOME10', 'PERCENT', 10, NULL, NULL, TRUE),
       ('GIAM50K',   'FIXED',  50000, 200000, 100, TRUE);
