-- ============================================================
-- Flyway V9: ban ghi thanh toan (callback tu cong thanh toan).
-- provider_ref UNIQUE -> khoa idempotency cho webhook.
-- ============================================================
CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT NOT NULL REFERENCES orders (id),
    provider     VARCHAR(32) NOT NULL,
    provider_ref VARCHAR(128) NOT NULL UNIQUE,
    amount       NUMERIC(12, 2) NOT NULL,
    status       VARCHAR(16) NOT NULL,
    created_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_payments_order ON payments (order_id);
